Repository man-group/pytest-plugins, pull requests merged in 2021-11, with the labels that each got.

#171 use stdlib unittest.mock on python 3
  pytest-profiling/tests/unit/test_profile.py
  pytest-server-fixtures/setup.py
  pytest-server-fixtures/tests/integration/test_jenkins_server.py
  pytest-server-fixtures/tests/integration/test_xvfb_server.py
  pytest-server-fixtures/tests/unit/serverclass/test_docker_unit.py
  pytest-server-fixtures/tests/unit/serverclass/test_kubernetes_unit.py
  pytest-server-fixtures/tests/unit/serverclass/test_thread_unit.py
  pytest-server-fixtures/tests/unit/test_server_unit.py
  pytest-server-fixtures/tests/unit/test_server_v2_unit.py
  pytest-shutil/pytest_shutil/run.py
  pytest-shutil/setup.py
  pytest-shutil/tests/integration/test_run_integration.py
  pytest-shutil/tests/unit/test_run.py
  pytest-verbose-parametrize/setup.py
  pytest-verbose-parametrize/tests/unit/test_verbose_parametrize.py
  pytest-virtualenv/setup.py
  pytest-virtualenv/tests/unit/test_venv.py
  pytest-webdriver/setup.py
  pytest-webdriver/tests/integration/test_integration.py
  pytest-webdriver/tests/unit/test_webdriver.py
Labels: bug, python2-compat

#170 pytest rethink update
  Makefile
  pytest-server-fixtures/pytest_server_fixtures/rethink.py
  pytest-server-fixtures/setup.py
Labels: bug

#164 Add: support to hide/show the full path of file
  pytest-profiling/pytest_profiling.py
Labels: enhancement
